import { imageUrl } from '@/utils/busUtils';

let layoutfore = {
  name: '版式4',
  imageUrl: imageUrl('/wx-images/clockin/lay4.png', true),
  id: '4',
  index: '4',
  useFlag: false,
  graph: [
    {
      w: 458,
      h: 458,
      x: 0,
      y: 0,
      type: 'image',
      dataIndex: 'imageUrl',
      value: '',
    },
    {
      type: 'rect',
      w: 458,
      h: 214,
      x: 0,
      y: 444,
      radius: '20 20 0 0',
      bgColor: 'rgba(247, 247, 247, 1)',
    },
    {
      w: 74,
      h: 74,
      x: 36,
      y: 480,
      type: 'image',
      dataIndex: 'avatarUrl',
      value: '',
      radius: 44,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'title',
      fontSize: 12,
      color: '#333333',
      isVertical: true,
      x: 362,
      y: 577,
    },
    {
      w: 58,
      h: 58,
      x: 380,
      y: 577,
      type: 'image',
      value: '',
      dataIndex: 'qrCode',
    },
    {
      type: 'text',
      id: '1',
      value: '',
      dataIndex: 'wordContent',
      lineHeight: 5,
      fontWeight: 'bold',
      fontSize: 18,
      color: '#333333',
      w: 300,
      x: 37,
      baseline: 'bottom',
      y: 636,
    },
    {
      type: 'rect',
      w: 1,
      h: 58,
      x: 274,
      y: 488,
      radius: '0',
      bgColor: 'rgba(204, 204, 209, 1)',
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCountText',
      fontSize: 19,
      color: '#333333',
      x: 155,
      y: 485,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCount',
      fontSize: 36,
      fontWeight: 'bold',
      color: '#333333',
      x: 163,
      y: 525,
      id: '2',
    },
    {
      type: 'text',
      value: '天',
      fontSize: 15,
      color: '#333333',
      follow: 'signCount',
      x: 6,
      y: 536,
      id: '3',
    },
    {
      type: 'text',
      value: '签到时间',
      fontSize: 19,
      x: 326,
      color: '#333333',
      y: 485,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signTime',
      fontSize: 36,
      fontWeight: 'bold',
      color: '#333333',
      x: 316,
      y: 525,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataDay',
      fontSize: 29,
      align: 'right',
      x: -42,
      y: 15,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataYearMonth',
      fontSize: 14,
      align: 'right',
      x: -31,
      y: 48,
    },
  ],
};

export default {
  layoutfore: layoutfore,
};
