import { imageUrl } from '@/utils/busUtils';

let layoutone = {
  name: '版式1',
  imageUrl: imageUrl('/wx-images/clockin/lay1.png', true),
  id: '1',
  index: '1',
  useFlag: false,
  backgroundUrl: '',
  backgroundColor: '',
  graph: [
    {
      w: 88,
      h: 88,
      x: 26,
      y: 544,
      type: 'image',
      dataIndex: 'avatarUrl',
      value: '',
      radius: 44,
    },
    {
      w: 88,
      h: 88,
      x: 544,
      y: 544,
      type: 'image',
      dataIndex: 'qrCode',
      value: '',
    },
    {
      type: 'text',
      id: '1',
      value: '',
      fontSize: 30,
      dataIndex: 'wordContent',
      lineHeight: 48,
      fontWeight: 'bold',
      w: 476,
      x: 27,
      y: 41,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCountText',
      fontSize: 22,
      x: 27,
      y: 432,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCount',
      fontSize: 44,
      fontWeight: 'bold',
      x: 28,
      y: 471,
      id: '2',
    },
    {
      type: 'text',
      value: '天',
      fontSize: 22,
      follow: 'signCount',
      x: 6,
      y: 484,
      id: '3',
    },
    {
      type: 'text',
      value: '签到时间',
      fontSize: 22,
      x: 182,
      y: 432,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signTime',
      fontSize: 44,
      fontWeight: 'bold',
      x: 182,
      y: 471,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataYearMonth',
      fontSize: 20,
      x: 133,
      y: 564,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataDay',
      fontSize: 20,
      follow: 'signDataYearMonth',
      extValueBefor: '.',
      x: 4,
      y: 564,
    },
    {
      type: 'text',
      value: '热爱美食让生活充满活力',
      fontSize: 22,
      x: 132,
      y: 591,
    },
  ],
};

export default {
  layoutone: layoutone,
};
