import { imageUrl } from '@/utils/busUtils';

let layoutzero = {
  name: '版式0',
  imageUrl: imageUrl('/wx-images/clockin/lay0.png', true),
  id: '0',
  index: '0',
  useFlag: true,
  backgroundUrl: '',
  backgroundColor: '',
  graph: [
    {
      w: 88,
      h: 88,
      x: 28,
      y: 28,
      type: 'image',
      value: '',
      dataIndex: 'avatarUrl',
      radius: 44,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'title',
      fontSize: 18,
      x: 542,
      y: 508,
    },
    {
      w: 84,
      h: 84,
      x: 543,
      y: 535,
      type: 'image',
      value: '',
      dataIndex: 'qrCode',
    },
    {
      type: 'text',
      id: '1',
      value: '',
      fontSize: 26,
      dataIndex: 'wordContent',
      lineHeight: 13,
      fontWeight: 'bold',
      baseline: 'bottom',
      w: 473,
      x: 28,
      y: 624,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCountText',
      fontSize: 26,
      x: 31,
      y: 167,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signCount',
      fontSize: 54,
      fontWeight: 'bold',
      x: 30,
      y: 213,
      id: '2',
    },
    {
      type: 'text',
      value: '天',
      fontSize: 22,
      follow: 'signCount',
      y: 232,
      x: 10,
      id: '3',
    },
    {
      type: 'text',
      value: '签到时间',
      fontSize: 26,
      x: 32,
      y: 300,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signTime',
      fontSize: 54,
      fontWeight: 'bold',
      x: 30,
      y: 344,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataDay',
      fontSize: 42,
      align: 'right',
      x: -29,
      y: 25,
    },
    {
      type: 'text',
      value: '',
      dataIndex: 'signDataYearMonth',
      fontSize: 20,
      align: 'right',
      x: -28,
      y: 75,
    },
  ],
};

export default {
  layoutzero,
};
